export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  CLIENTS: '/clients',
  CLIENT_PROFILE: '/clients/:id',
  PAYMENTS: '/payments',
  SHIFTS: '/shifts',
  ATTENDANCE: '/attendance',
  CALENDAR: '/calendar',
  EXPENSES: '/expenses',
  MEMBERSHIPS: '/memberships',
  DASHBOARD: '/dashboard',
  USERS: '/usuarios',
  SETTINGS: '/settings',
} as const
