export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  CLIENTS: '/clients',
  CLIENT_NEW: '/clients/new',
  CLIENT_PROFILE: '/clients/:id',
  CLIENT_RUTINA: '/clients/:id/rutina',
  PAYMENTS: '/payments',
  PAYMENT_DETAIL: '/payments/:id',
  SHIFTS: '/shifts',
  SHIFT_DETAIL: '/shifts/:id',
  ATTENDANCE: '/attendance',
  CALENDAR: '/calendar',
  EXPENSES: '/expenses',
  MEMBERSHIPS: '/memberships',
  DASHBOARD: '/dashboard',
  USERS: '/usuarios',
  SETTINGS: '/settings',
  EXERCISES: '/exercises',
} as const
